### ISSUE TITLE
`limgo-action@v1.0.1` uses deprecated Node.js 16

### ISSUE THREAD

**Issue by webbnh** [GoTestTools/limgo-action#1]
My workflow is producing the following annotation:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: GoTestTools/limgo-action@v1.0.1.
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

Is an updated release of `limgo-action` forthcoming?

**Comment by engelmi** [comment]
Hi @webbnh, 
I created a new release [v1.0.2](https://github.com/GoTestTools/limgo-action/releases/tag/v1.0.2) for `limgo-action` which uses Node.js 20 instead of Node.js 16. 
Could you update your workflow? The warning should be gone then.

**Comment by webbnh** [comment]
Hi @engelmi, it looks good!

Thanks for the incredible responsiveness!!
